# Generated by Django 4.0 on 2021-12-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='referral',
            name='referring_staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referral.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referral.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referral.program'),
            preserve_default=False,
        ),
    ]
